#!/usr/bin/env bash

# /usr/bin/start-capture

sudo pkill tcpdump
rm -rf *.pcap

if [[ $1 != *"GET.pcap"* ]] && [[ $1 != *"POST.pcap"* ]] && \
   [[ $1 != *"PUT.pcap"* ]] && [[ $1 != *"DELETE.pcap"* ]];then
        echo -e "\nUsage is:\n"
        echo -e "  start-capture <your first name>-<GET|POST|PUT|DELETE>.pcap\n"
        exit
fi

sudo tcpdump -vvvv -i any -w $1 port 9696 or http > /dev/null 2>&1 &
echo -e "\nCapture started! Run any neutron command.\n"
