#!/usr/bin/env bash

# /usr/bin/stop-capture

sudo pkill tcpdump
sleep 1
cp *.pcap Cisco-Live-Workshop/captures
rm -rf *.pcap
cd Cisco-Live-Workshop
git add *
git commit -m "Cisco Live commit"
git push origin master
cd ..
echo -e "\nCapture ended\n"
